# Generated by Django 2.2.5 on 2021-06-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('continent', models.CharField(max_length=200)),
                ('population', models.IntegerField()),
                ('weeky_count', models.IntegerField()),
                ('rate_14_day', models.FloatField()),
                ('cumulation_count', models.IntegerField()),
            ],
            options={
                'db_table': 'index_table',
                'managed': False,
            },
        ),
    ]
