# Generated by Django 2.2.5 on 2021-06-16 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='index_model',
            table='covid_plataform.index_table',
        ),
    ]
