# Generated by Django 2.2.5 on 2021-06-16 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_app', '0002_auto_20210616_0153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='index_model',
            table='index_table',
        ),
    ]
