# Generated by Django 2.2.5 on 2021-06-16 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_app', '0005_auto_20210616_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index_model',
            options={'managed': False},
        ),
    ]
