# Generated by Django 2.2.5 on 2021-06-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_app', '0006_auto_20210616_0203'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='index_model',
            table='public.index_table',
        ),
    ]
