# Generated by Django 2.2.5 on 2021-06-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_app', '0007_auto_20210616_0209'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='index_model',
            table='index_table',
        ),
    ]
