# Generated by Django 2.2.5 on 2021-06-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_app', '0008_auto_20210616_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='top_15_cases_deaths',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('continent', models.CharField(max_length=200)),
                ('population', models.IntegerField()),
                ('weekly_count', models.IntegerField()),
                ('rate_14_day', models.FloatField()),
                ('cumulative_count', models.IntegerField()),
            ],
            options={
                'db_table': 'top_15_cases_deaths',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='index_model',
        ),
    ]
